#!/bin/zsh 

# set title to either the first parameter, or the hostname if there are no
# parameters on the command line

#set -x
STITLE="localhost" # `hostname`

while [ 1 ]; do
  case x$1 in
    x)
      break
      ;;
    x-p)
      shift 1
      ;;
    x-*)
      ;;
    *)
      NOUNAME=`print $1 | sed 's/.*@//'`
      print $NOUNAME | egrep '([[:digit:]]{1,3}\.){3}[[:digit:]]{1,3}' > /dev/null
      if [ $? = 0 ]; then # this is an IP address instead of a hostname
        STITLE=$NOUNAME
      else # this is a hostname, strip the domain part
        STITLE=`print $NOUNAME | sed 's/\..*//'`
      fi
      break
      ;;
  esac
  shift 1
done


# strip out the domain part, just show the hostname
STITLE=`echo $STITLE | awk -F. '{print $1}'`



case $TERM in
  xterm*)
    # change the title to be more descriptive
    precmd () { print -Pn "\e]0;%n@%m: %~\a" }
    ;;
  screen*)
    # set the screen title, not the terminal title
    precmd () { print -Pn "\ek$STITLE\e\\" }
    ;;
esac

